// angular/src/app/game-header/game-header.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-game-header',
  templateUrl: './game-header.component.html',
  styleUrls: ['./game-header.component.css']
})
export class GameHeaderComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}

<div>
  <img src="favicon.ico" alt="logo" />
  <h1>Game of Life</h1>
</div>

// vue/src/components/GameHeader.vue
<template>
  <div class="App-header">
    <img src="favicon.ico" class="App-logo" alt="logo" />
    <h1 className="App-title">{{ title }}</h1>
  </div>
</template>

<script>
export default {
  name: 'GameHeader',
  data () {
    return {
      title: 'Game of Life'
    }
  }
}
</script>

<style scoped>

.App-logo {
  animation: App-logo-scale infinite 4s linear;
  height: 80px;
  width: 80px;
}

.App-header {
  background-color: #000;
  height: 130px;
  padding: 20px;
  color: aliceblue;
}

.App-title {
  font-size: 1.5em;
}

@keyframes App-logo-scale {
  from { transform: scale(0.8); }
  to { transform: scale(1.2); }
}

</style>
