// react/src/GameButtons.jsx
import React from 'react';
import Button from './Button';

const GameButtons = (props) =>
  <div className="Game-buttons">
    <Button className="game-button" label="Random" value="random" onClick={props.changeGameState} />
    <Button className="game-button" label="Start"  value="start"  onClick={props.changeGameState} />
    <Button className="game-button" label="Stop"   value="stop"   onClick={props.changeGameState} />
    <Button className="game-button" label="Reset"  value="reset"  onClick={props.changeGameState} />
  </div>;

export default GameButtons;

// vue/src/components/GameButtons.vue
<template>
  <div class="Game-buttons">
    <button @click="clickAction('random')" value="Random">Random</button>
    <button @click="clickAction('start')" value="Start">Start</button>
    <button @click="clickAction('stop')" value="Stop">Stop</button>
    <button @click="clickAction('reset')" value="Reset">Reset</button>
  </div>
</template>

<script>
export default {
  name: 'GameButtons',
  props: {
    clickAction: {
      type: Function,
      required: true
    }
  }
}
</script>

<style scoped>

.Game-buttons {
  width: 100%;
  margin-top: 20px;
}

</style>
