// vue/src/components/GameButtons.vue
<template>
  <div class="Game-buttons">
    <button @click="clickAction('random')" value="Random">Random</button>
    <button @click="clickAction('start')" value="Start">Start</button>
    <button @click="clickAction('stop')" value="Stop">Stop</button>
    <button @click="clickAction('reset')" value="Reset">Reset</button>
  </div>
</template>

<script>
export default {
  name: 'GameButtons',
  props: {
    clickAction: {
      type: Function,
      required: true
    }
  }
}
</script>

<style scoped>

.Game-buttons {
  width: 100%;
  margin-top: 20px;
}

</style>

// react/src/GameButtons.js
import React from 'react';
import Button from './Button';

const GameButtons = (props) =>
  <div style={{ width: '100%' }}>
    <Button className="game-button" label="random" onClick={props.actionRandom} />
    <Button className="game-button" label="reset" onClick={props.actionReset} />
    <Button className="game-button" label="start" onClick={props.actionStart} />
  </div>;

export default GameButtons;
