// vue/src/components/GameArea.vue
<template>
  <section class="Game-area">
    <GameOfLife :cellulesWidth="50" :cellulesHeight="40"></GameOfLife>
    <GameButtons :clickAction="changeGameState"></GameButtons>
  </section>
</template>

<script>
import GameButtons from './GameButtons'
import GameOfLife from './GameOfLife'

export default {
  name: 'GameArea',
  components: {
    GameOfLife,
    GameButtons
  },
  methods: {
    changeGameState(gameState) {
      this.$emit('gameStateUpdated', gameState);
    }
  }
}
</script>

<style scoped>

.Game-area {
  width: 94%;
  height: 510px;
  max-width: 500px;
  margin: 0 auto;
}

</style>

// react/src/GameArea.jsx
import React, { Component } from 'react';
import GameOfLife from './GameOfLife';
import GameButtons from './GameButtons';

class GameArea extends Component {

  constructor(props) {
    super(props);
    this.changeGameState = this.changeGameState.bind(this);
    this.state = { gameState: 'stop' };
  }

  changeGameState(e) {
    this.setState({ gameState: e.target.value });
  }

  render () {
    return (
      <section className="Game-area">
        <GameOfLife cellulesWidth={50} cellulesHeight={40} gameState={this.state.gameState} />
        <GameButtons changeGameState={this.changeGameState} />
      </section>
    );
  }

}
export default GameArea;
