// react/src/GameFooter.jsx
import React from 'react';

const GameFooter = () =>
  <footer className="App-footer">
    <strong className="Footer-text">
      Game of Life - a react experiment &nbsp;
      <a href="https://github.com/diegocardoso93/game-of-life"
         target="_blank"
         rel="noopener noreferrer">source</a>
    </strong>
  </footer>;

export default GameFooter;

// angular/src/app/game-footer/game-footer.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-game-footer',
  templateUrl: './game-footer.component.html',
  styleUrls: ['./game-footer.component.css']
})
export class GameFooterComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}

<footer ngClass="app-footer">
  <strong ngClass="footer-text">
    Game of Life - a react experiment &nbsp;
    <a href="https://github.com/diegocardoso93/game-of-life"
       target="_blank"
       rel="noopener noreferrer">source</a>
  </strong>
</footer>
