// react/src/GameButtons.jsx
import React from 'react';
import Button from './Button';

const GameButtons = (props) =>
  <div className="Game-buttons">
    <Button className="game-button" label="Random" value="random" onClick={props.changeGameState} />
    <Button className="game-button" label="Start"  value="start"  onClick={props.changeGameState} />
    <Button className="game-button" label="Stop"   value="stop"   onClick={props.changeGameState} />
    <Button className="game-button" label="Reset"  value="reset"  onClick={props.changeGameState} />
  </div>;

export default GameButtons;

// angular/src/app/game-buttons/game-buttons.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-game-buttons',
  templateUrl: './game-buttons.component.html',
  styleUrls: ['./game-buttons.component.css']
})
export class GameButtonsComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}

<div ngClass="game-buttons">
  <app-button ngClass="game-button" label="Random" value="random"></app-button>
  <app-button ngClass="game-button" label="Start"  value="start" ></app-button>
  <app-button ngClass="game-button" label="Stop"   value="stop"  ></app-button>
  <app-button ngClass="game-button" label="Reset"  value="reset" ></app-button>
</div>
